-- ============================================================
-- page_views 表：记录每一次页面访问
-- 运行位置：Supabase SQL Editor（Dashboard → SQL Editor → New Query）
-- ============================================================

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  page text not null default '/',
  referrer text default '',
  screen text default '',
  language text default '',
  url text default '',
  date text not null,
  hour int not null default 0,
  created_at timestamptz default now()
);

-- 索引，加速统计查询
create index if not exists idx_page_views_date on public.page_views (date);
create index if not exists idx_page_views_page on public.page_views (page);
create index if not exists idx_page_views_created on public.page_views (created_at desc);

-- RLS：关闭（个人小站，数据不重要，简化处理）
alter table public.page_views disable row level security;
